language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/db_test

node_js:  
  - "12"

before_script:
  - psql -c 'create database  db_test;' -U postgres
  - psql -U postgres -d db_test -a -f db.sql

services:
  - postgresql
